name: CI Build1

on:
  workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@main
      with:
        allowed-endpoints: 
          api.nuget.org:443
          dotnetcli.azureedge.net:443
          dc.services.visualstudio.com:443
          dotnetcli.blob.core.windows.net:443
          github.com:443
          raw.githubusercontent.com:443
    - uses: actions/checkout@v1
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Build with dotnet
      run: ./build.sh --linksources=true --verbosity=verbose
      shell: bash   
