name: CI Build1

on:
  workflow_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@int
      with:
        egress-policy: audit
    
    - uses: actions/checkout@v3
    - run: cat InventoryManager.cs  
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.*
    - name: Build with dotnet
      run: |
        echo "123" >> InventoryManager.cs
        cat InventoryManager.cs
      shell: bash 
    - run: cat InventoryManager.cs  
